---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kafka-nineinfra-tech-v1-kafkacluster
  failurePolicy: Fail
  name: mkafkacluster.kb.io
  rules:
  - apiGroups:
    - kafka.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kafka-nineinfra-tech-v1-kafkacluster
  failurePolicy: Fail
  name: vkafkacluster.kb.io
  rules:
  - apiGroups:
    - kafka.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kafkaclusters
  sideEffects: None
