---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kafka.nineinfra.tech
  resources:
  - kafkaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.nineinfra.tech
  resources:
  - kafkaclusters/finalizers
  verbs:
  - update
- apiGroups:
  - kafka.nineinfra.tech
  resources:
  - kafkaclusters/status
  verbs:
  - get
  - patch
  - update
